### PR TITLE
Display markers with fetch

### PR DESCRIPTION
**Pull request by TBarrett553**
Right now it seems as if the filter instances associated with Query are deprecated. However, according to the documentation, what I used was fine. I think this problem has also led to the fetch JS method falling through. In addition, I keep getting this weird error about the some cross-site cookie that is now being blocked due to security concerns. I will post the resources I've been using under this so I can get some help.

### CODE REVIEW

**Comment by TBarrett553** [comment]
Here is documentation about what I used in datastore (Legacy reference): 
[https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/Query.FilterPredicate](url)

Here is information about the cookie error: [https://www.chromestatus.com/feature/5088147346030592](url)

**Comment by flying-bus** [comment]
> Here is documentation about what I used in datastore (Legacy reference):
> [https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/Query.FilterPredicate](url)
> 
> Here is information about the cookie error: [https://www.chromestatus.com/feature/5088147346030592](url)

I took a look at the cookie warnings, and while they're concerning it doesn't look like it's breaking any functionality at the moment. So I advised Teanna to continue working on displaying the markers with fetch (either on the main page, or potentially on a separate "view" page).

**Comment by TBarrett553** [comment]
I just pushed a new commit to integrate the UUID from the marker

**Comment by flying-bus** [comment]
> I just pushed a new commit to integrate the UUID from the marker

Hmm - is github having problems again? I don't see the commit.

**Comment by TBarrett553** [comment]
Actually, I realized later that I pushed the UUID update to the JS filter function. So that is the PR to display markers stored in the Datastore

**Comment by TBarrett553** [comment]
I will probably close down this branch because the JSFilterbyBoundary branch is better at addressing the issues linked to this PR

**Pull request closed without merging**
