### PR TITLE
Nav bar footer

### PR DESCRIPTION
**Pull request by ayomide321**
Updated the HTML doc with better formatting for the form popup button. In addition added a "header" and a "footer". Deleted the walkthroughs file and updated the README file to talk about the maptivist project. 

TODO:
Connect form to backend
add links for the footer 
connect the

### CODE REVIEW

**Comment by flying-bus** [comment]
Can you get #6 merged into master first? That will make the diff easier to read.

I also suggest waiting until after Teanna deletes the extra directories and does the source director rename.

**Comment by ayomide321** [comment]
> Can you get #6 merged into master first? That will make the diff easier to read.
> 
> I also suggest waiting until after Teanna deletes the extra directories and does the source director rename.

Now that Teannas branch has been merged, is this one good to go?

**Review by freeboson — APPROVED** [review]
LGTM, it looks like some of the changes were submitted through your other PR. Merge in the current master, and should be good to go.

**Review by TBarrett553 — APPROVED** [review]
Lgtm

**Pull request merged**
